[package]
name = "wasvy"
authors.workspace = true
categories.workspace = true
rust-version.workspace = true
version.workspace = true
edition.workspace = true
description.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
readme.workspace = true
publish = true

[workspace]
members = ["examples/host_example", "examples/simple"]
resolver = "2"

[workspace.package]
authors = ["EngoDev"]
categories = ["wasm", "game-development"]
rust-version = "1.88.0"
version = "0.0.3"
edition = "2024"
description = "Bevy WASM"
license = "MIT OR Apache-2.0"
homepage = "https://crates.io/crates/wasvy"
repository = "https://github.com/EngoDev/wasvy"
readme = "README.md"

[workspace.dependencies]
anyhow = "1.0.99"
bevy = { version = "0.17.1", features = ["serialize"] }
bevy_reflect = "0.17.1"
bevy_transform = { version = "0.17.1", features = [
    "serialize",
], default-features = false }
bevy_math = { version = "0.17.1", features = [
    "std",
    "serialize",
], default-features = false }
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.143"
thiserror = "2.0.16"
wasmtime = { version = "36.0.2", features = ["component-model"] }
wasmtime-wasi = "36.0.2"
wit-bindgen = { version = "0.46.0", features = ["bitflags"] }

[dependencies]
anyhow.workspace = true
bevy.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
wasmtime.workspace = true
wasmtime-wasi.workspace = true
