// We actually don't use this; it's just to let bindgen! ind the corresponding world in wit/deps.
package component:simple;

/// An example world for the component to target.
world example {
    use wasvy:ecs/system-params.{commands, query-results};

    /// An example system
    export my-system: func(commands: commands, query: query-results);

    /// This is important.
    /// This makes it so the WASM module must implement the guest required functions by the Bevy host.
    include wasvy:ecs/guest;
}
