package component:simple;


/// An example world for the component to target.
world example {
	import wasvy:ecs/functions;
	/// This is important.
	/// This makes it so the WASM module must implement the guest required functions by the Bevy host.
	include wasvy:ecs/guest;

	use wasvy:ecs/types.{query-result};

	/// This exported function can't be called automatically from Wasvy
	/// because it doesn't comply to the desired signature.
    export hello-world: func() -> string;

    /// All systems must only have one argument of type `list<query-result>`
	export print-first-component-system: func(params: list<query-result>);
}
